using Microsoft.EntityFrameworkCore;
using ShelfWise.Domain.Models;

namespace ShelfWise.Repository.Data
{
    public static class DbInitializer
    {
        public static void Initialize(AppDbContext context)
        {
            context.Database.Migrate();
            EnsureSchema(context);

            if (!context.Books.Any())
            {
                var books = new List<Book>
                {
                    new Book { Title = "The Pragmatic Programmer", Author = "Andrew Hunt", Category = Category.NonFiction, Genre = "Technical", TotalCopies = 3 },
                    new Book { Title = "Clean Code", Author = "Robert C. Martin", Category = Category.NonFiction, Genre = "Technical", TotalCopies = 2 },
                    new Book { Title = "Domain-Driven Design", Author = "Eric Evans", Category = Category.NonFiction, Genre = "Technical", TotalCopies = 1 }
                };

                context.Books.AddRange(books);
                context.SaveChanges();
            }

            if (!context.Users.Any())
            {
                var devUser = new ShelfWise.Domain.Models.User
                {
                    FirstName = "Dev",
                    LastName = "User"
                };
                context.Users.Add(devUser);
                context.SaveChanges();
            }
        }

        private static void EnsureSchema(AppDbContext context)
        {
            context.Database.ExecuteSqlRaw("""
                CREATE TABLE IF NOT EXISTS "Books" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Title" text NOT NULL,
                    "Author" text NOT NULL,
                    "Category" integer NOT NULL,
                    "Genre" text NOT NULL,
                    "TotalCopies" integer NOT NULL,
                    CONSTRAINT "PK_Books" PRIMARY KEY ("Id")
                );

                CREATE TABLE IF NOT EXISTS "Users" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "FirstName" text NOT NULL,
                    "LastName" text NOT NULL,
                    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
                );

                CREATE TABLE IF NOT EXISTS "BorrowRecords" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "BookId" integer NOT NULL,
                    "UserId" integer NOT NULL,
                    "CheckedOutAt" timestamp with time zone NOT NULL,
                    "DueAt" timestamp with time zone NOT NULL,
                    "ReturnedAt" timestamp with time zone NULL,
                    CONSTRAINT "PK_BorrowRecords" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_BorrowRecords_Books_BookId" FOREIGN KEY ("BookId") REFERENCES "Books" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_BorrowRecords_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS "HoldRecords" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "BookId" integer NOT NULL,
                    "UserId" integer NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "NotifiedAt" timestamp with time zone NULL,
                    "ExpiresAt" timestamp with time zone NULL,
                    CONSTRAINT "PK_HoldRecords" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_HoldRecords_Books_BookId" FOREIGN KEY ("BookId") REFERENCES "Books" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_HoldRecords_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS "IX_BorrowRecords_BookId" ON "BorrowRecords" ("BookId");
                CREATE INDEX IF NOT EXISTS "IX_BorrowRecords_UserId" ON "BorrowRecords" ("UserId");
                CREATE INDEX IF NOT EXISTS "IX_HoldRecords_BookId" ON "HoldRecords" ("BookId");
                CREATE INDEX IF NOT EXISTS "IX_HoldRecords_UserId" ON "HoldRecords" ("UserId");
                """);
        }
    }
}
